name: Build And Push to ECR

on:
  push:
    branches: [ 'main' ]

# 🚨 CRITICAL: This allows GitHub to request short-lived temporary tokens from AWS OIDC
permissions:
  id-token: write
  contents: read

jobs:
  build_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (Tokenless OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::964775859386:role/my-github-actions-role

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: docker build -t 964775859386.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest .

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '964775859386.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: push to ECR
        run: docker push 964775859386.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest